{
 "title": "Strom",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Energie",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "target": "0f746430-d39e-11e7-9f92-2f38b410ecdc",
     "type": "timeseries"
    },
    {
     "target": "88b7ece0-a3b2-11e8-800c-d7842b5a9bbe",
     "type": "timeseries"
    },
    {
     "target": "a9616e80-a3b2-11e8-aa5e-0d1e58eab27e",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Leistung nach Phasen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "data": "{\"tuples\":100}",
     "target": "607d0ba0-d283-11e7-afb6-bd6a69803885",
     "type": "timeseries"
    },
    {
     "data": "{\"tuples\":100}",
     "target": "63d1cb10-d283-11e7-9481-9fdd0cb8679d",
     "type": "timeseries"
    },
    {
     "data": "{\"tuples\":100}",
     "target": "66df03c0-d283-11e7-9544-d7844733cf6f",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "PV Stündlich",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "data": "{\"mode\":\"consumption\",\"group\":\"hour\"}",
     "target": "0f746430-d39e-11e7-9f92-2f38b410ecdc",
     "type": "timeseries"
    },
    {
     "data": "{\"mode\":\"consumption\",\"group\":\"hour\"}",
     "target": "19f2ef70-d39e-11e7-b2e8-f552c3dac8a7",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Prognose Erzeugung (heute)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 8 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "data": "{\"context\":\"prognosis\",\"period\":\"day\"}",
     "target": "0f746430-d39e-11e7-9f92-2f38b410ecdc",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Prognose Bezug (heute)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 8 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "data": "{\"context\":\"prognosis\",\"period\":\"day\"}",
     "target": "88b7ece0-a3b2-11e8-800c-d7842b5a9bbe",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Historie Tägliche Erzeugung",
   "type": "table",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 13 },
   "targets": [
    {
     "data": "{\"options\":\"consumption\",\"group\":\"day\"}",
     "target": "0f746430-d39e-11e7-9f92-2f38b410ecdc",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "PV Täglich",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "data": "{\"options\":\"consumption\",\"group\":\"day\"}",
     "target": "0f746430-d39e-11e7-9f92-2f38b410ecdc",
     "type": "timeseries"
    },
    {
     "data": "{\"options\":\"consumption\",\"group\":\"day\"}",
     "target": "19f2ef70-d39e-11e7-b2e8-f552c3dac8a7",
     "type": "timeseries"
    }
   ]
  }
 ]
}